"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2 } from "lucide-react";
import { formatCurrency } from "@/lib/utils";
import type { AuditFinding } from "@/lib/audit-engine";

interface Branding { agencyName?: string | null; agencyLogo?: string | null; plan?: string }

export function ExportPDFButton({ audit, branding }: { audit: Record<string, unknown>; branding?: Branding }) {
  const [loading, setLoading] = useState(false);

  async function exportPDF() {
    setLoading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      const pageW = 210;
      const margin = 20;
      let y = 20;

      const isWhiteLabel = branding?.agencyName && ["GROWTH", "AGENCY"].includes(branding?.plan ?? "");
      const headerTitle = isWhiteLabel ? `${branding!.agencyName} — Conversion Audit` : "AuditRoast Audit Report";
      const footerText = isWhiteLabel ? `Prepared by ${branding!.agencyName}` : "Generated by AuditRoast.com — AI Website Conversion Auditor";

      // Header
      doc.setFillColor(109, 40, 217);
      doc.rect(0, 0, pageW, 40, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text(headerTitle, margin, 20);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(String(audit.url), margin, 30);
      doc.text(new Date().toLocaleDateString("en-GB"), pageW - margin, 30, { align: "right" });

      y = 55;

      // Scores
      doc.setTextColor(30, 30, 30);
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Conversion Scores", margin, y);
      y += 8;

      const scores = [
        ["Overall", audit.overallScore],
        ["Trust", audit.trustScore],
        ["UX", audit.uxScore],
        ["SEO", audit.seoScore],
        ["Mobile", audit.mobileScore],
        ["Revenue", audit.revenueScore],
      ] as [string, number][];

      scores.forEach(([label, score], i) => {
        const x = margin + (i % 3) * 58;
        const scoreY = y + Math.floor(i / 3) * 28;
        doc.setFillColor(245, 243, 255);
        doc.roundedRect(x, scoreY, 52, 22, 3, 3, "F");
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(109, 40, 217);
        doc.text(String(score ?? 0), x + 10, scoreY + 13);
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 100, 100);
        doc.text(label, x + 10, scoreY + 20);
      });

      y += 65;

      // Revenue opportunity
      if (audit.revenueOpportunity) {
        doc.setFillColor(240, 253, 244);
        doc.roundedRect(margin, y, pageW - margin * 2, 25, 3, 3, "F");
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(21, 128, 61);
        doc.text(`Revenue Opportunity: ${formatCurrency(Number(audit.revenueOpportunity))}/month`, margin + 5, y + 10);
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(22, 101, 52);
        doc.text(`Current conv. rate: ${((Number(audit.currentConvRate) || 0) * 100).toFixed(1)}%  →  Potential uplift: +${((Number(audit.potentialUplift) || 0) * 100).toFixed(1)}%`, margin + 5, y + 19);
        y += 33;
      }

      // Findings
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 30);
      doc.text("Key Findings & Recommendations", margin, y);
      y += 8;

      const findings = (audit.recommendations as AuditFinding[]) ?? [];
      findings.forEach((f, i) => {
        if (y > 260) {
          doc.addPage();
          y = 20;
        }

        const priorityColor: [number, number, number] =
          f.priority === "HIGH" ? [220, 38, 38] :
          f.priority === "MEDIUM" ? [217, 119, 6] :
          [107, 114, 128];

        doc.setFillColor(...priorityColor);
        doc.roundedRect(margin, y, pageW - margin * 2, 32, 2, 2, "F");

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.text(`${i + 1}. [${f.priority}] ${f.category}: ${f.issue}`, margin + 3, y + 8);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        const impactLines = doc.splitTextToSize(`Fix: ${f.fix}`, pageW - margin * 2 - 6);
        doc.text(impactLines[0], margin + 3, y + 16);
        doc.text(`Revenue Impact: ${f.revenueImpact}`, margin + 3, y + 26);
        y += 38;
      });

      // Footer
      doc.setTextColor(150, 150, 150);
      doc.setFontSize(8);
      doc.text(footerText, pageW / 2, 290, { align: "center" });

      doc.save(`roastmysite-audit-${Date.now()}.pdf`);
    } finally {
      setLoading(false);
    }
  }

  return (
    <Button variant="secondary" onClick={exportPDF} disabled={loading}>
      {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
      Export PDF
    </Button>
  );
}

