import Link from "next/link";
import { Flame } from "lucide-react";

export const metadata = {
  title: "Terms of Service — Profitlens",
  description: "Terms and conditions for using Profitlens.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#09090b]">
      <nav className="border-b border-white/5 bg-[#09090b]/80 backdrop-blur-xl">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-gradient-to-br from-violet-600 to-purple-600 rounded-lg flex items-center justify-center">
              <Flame className="w-5 h-5 text-white" />
            </div>
            <span className="font-bold text-lg text-white">Profitlens</span>
          </Link>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-4xl font-extrabold text-white mb-3">Terms of Service</h1>
        <p className="text-gray-500 text-sm mb-12">Last updated: June 2025</p>

        <div className="space-y-10 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Profitlens (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
            <p>
              Profitlens provides AI-powered website conversion auditing. You submit a URL and receive an automated analysis of conversion-related issues, scores, and recommendations. Results are generated by AI and are estimates — they are not a guarantee of any specific outcome or revenue increase.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Accounts</h2>
            <ul className="space-y-2 list-disc list-inside text-gray-400">
              <li>You must provide accurate information when creating an account.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>You must be at least 18 years old to use the Service.</li>
              <li>We reserve the right to suspend or terminate accounts that violate these terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="space-y-2 list-disc list-inside text-gray-400">
              <li>Submit URLs to websites you do not own or do not have permission to audit.</li>
              <li>Use the Service to audit websites containing illegal content.</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the Service&apos;s AI infrastructure.</li>
              <li>Resell or redistribute audit results without permission (except as permitted under Agency plan terms).</li>
              <li>Use automated tools to abuse the free audit limit.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Payments & Subscriptions</h2>
            <ul className="space-y-2 list-disc list-inside text-gray-400">
              <li>Paid plans are billed monthly via Stripe.</li>
              <li>Prices are listed in GBP and are exclusive of any applicable taxes.</li>
              <li>Unused audit credits do not roll over between billing periods.</li>
              <li>You may cancel your subscription at any time. Access continues until the end of the current billing period.</li>
              <li>We reserve the right to change pricing with 30 days&apos; notice to existing subscribers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Refunds</h2>
            <p>
              We offer a 7-day money-back guarantee on all paid plans. See our{" "}
              <Link href="/refunds" className="text-violet-400 hover:text-violet-300">Refund Policy</Link>{" "}
              for full details.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Intellectual Property</h2>
            <p>
              The Profitlens platform, branding, and software are owned by us and protected by copyright. Audit reports generated for your website are yours to use. You may not use the Profitlens name, logo, or brand without written permission.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Disclaimer of Warranties</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind. AI-generated audit results are estimates based on automated analysis and may not reflect every issue on your website. We do not guarantee that following our recommendations will result in any specific improvement to your conversion rate or revenue.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Profitlens shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability for any claim shall not exceed the amount you paid us in the 3 months prior to the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Governing Law</h2>
            <p>
              These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Changes to Terms</h2>
            <p>
              We may update these Terms at any time. We will notify you of material changes via email. Continued use of the Service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">12. Contact</h2>
            <p>
              Questions about these Terms? Email{" "}
              <a href="mailto:support@profitlens.com" className="text-violet-400 hover:text-violet-300">support@profitlens.com</a>.
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-white/5 flex gap-6 text-sm text-gray-500">
          <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
          <Link href="/refunds" className="hover:text-white transition-colors">Refund Policy</Link>
          <Link href="/" className="hover:text-white transition-colors">Home</Link>
        </div>
      </div>
    </div>
  );
}
